name: Build and Push Docker to Dockerhub

on:
    push:
      branches:
        - main

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
            name: main
    steps:
        - uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to GitHub container registry
          uses: docker/login-action@v3
          with:
            # registry: ghcr.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PAT }}
        
        - name: Build and push container image to registry
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{ secrets.DOCKER_REPO_NAME }}:${{ github.sha }}
            file: ./Dockerfile